@startuml

title __MAXPROP's Class Diagram__\n

  namespace routing {
    namespace maxprop {
      class routing.maxprop.MaxPropDijkstra {
          {static} - INFINITY : Double
          {static} - PQ_INIT_SIZE : int
          - prevNodes : Map<Integer, Integer>
          - probs : Map<Integer, MeetingProbabilitySet>
          - unvisited : Queue<Integer>
          - visited : Set<Integer>
          + MaxPropDijkstra()
          + getCosts()
          - getDistance()
          - initWith()
          - relax()
          - setDistance()
      }
    }
  }
  

  namespace routing {
    namespace maxprop {
      class routing.maxprop.MaxPropDijkstra.DistanceComparator {
          + compare()
      }
    }
  }
  

  namespace routing {
    namespace maxprop {
      class routing.maxprop.MaxPropDijkstra.DistanceMap {
          - map : HashMap<Integer, Double>
          + DistanceMap()
          + get()
          + put()
          + toString()
      }
    }
  }
  

  namespace routing {
    namespace maxprop {
      class routing.maxprop.MeetingProbabilitySet {
          {static} + INFINITE_SET_SIZE : int
          - alpha : double
          - lastUpdateTime : double
          - maxSetSize : int
          - probs : Map<Integer, Double>
          + MeetingProbabilitySet()
          + MeetingProbabilitySet()
          + MeetingProbabilitySet()
          + getAllProbs()
          + getLastUpdateTime()
          + getProbFor()
          + replicate()
          + setAlpha()
          + toString()
          + updateMeetingProbFor()
          + updateMeetingProbFor()
      }
    }
  }
  

  routing.maxprop.MaxPropDijkstra o-- routing.maxprop.MaxPropDijkstra.DistanceMap : distancesFromStart
  routing.maxprop.MaxPropDijkstra +-down- routing.maxprop.MaxPropDijkstra.DistanceComparator
  routing.maxprop.MaxPropDijkstra +-down- routing.maxprop.MaxPropDijkstra.DistanceMap
  routing.maxprop.MaxPropDijkstra.DistanceComparator .up.|> java.util.Comparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
