@startuml

title __PLAYFIELD's Class Diagram__\n

  namespace gui {
    namespace playfield {
      class gui.playfield.MapGraphic {
          - BG_COLOR : Color
          - PATH_COLOR : Color
          + MapGraphic()
          + draw()
      }
    }
  }
  

  namespace gui {
    namespace playfield {
      class gui.playfield.MessageGraphic {
          - msgColor : Color
          + MessageGraphic()
          + draw()
      }
    }
  }
  

  namespace gui {
    namespace playfield {
      class gui.playfield.NodeGraphic {
          {static} - conColor : Color
          {static} - drawBuffer : boolean
          {static} - drawConnections : boolean
          {static} - drawCoverage : boolean
          {static} - drawNodeName : boolean
          {static} - highlightedNodeColor : Color
          {static} - highlightedNodes : List<DTNHost>
          {static} - hostColor : Color
          {static} - hostNameColor : Color
          {static} - msgColor1 : Color
          {static} - msgColor2 : Color
          {static} - msgColor3 : Color
          {static} - rangeColor : Color
          + NodeGraphic()
          + draw()
          {static} + setDrawBuffer()
          {static} + setDrawConnections()
          {static} + setDrawCoverage()
          {static} + setDrawNodeName()
          {static} + setHighlightedNodes()
          - drawBar()
          - drawHost()
          - drawMessages()
          - isHighlighted()
      }
    }
  }
  

  namespace gui {
    namespace playfield {
      class gui.playfield.PathGraphic {
          {static} - PATH_COLOR : Color
          - coords : List<Coord>
          + PathGraphic()
          + draw()
      }
    }
  }
  

  namespace gui {
    namespace playfield {
      class gui.playfield.PlayField {
          {static} + PLAYFIELD_OFFSET : int
          - autoClearOverlay : boolean
          - bgColor : Color
          - curTransform : AffineTransform
          - focusOnClick : boolean
          - imageTransform : AffineTransform
          - overlayGraphics : List<PlayFieldGraphic>
          - showMapGraphic : boolean
          - underlayImage : BufferedImage
          - underlayImgDx : double
          - underlayImgDy : double
          + PlayField()
          + addMessageTransfer()
          + addPath()
          + clearOverlays()
          + getGraphicsPosition()
          + getWorldPosition()
          + paint()
          + setAutoClearOverlay()
          + setFocusOnClick()
          + setMap()
          + setScale()
          + setShowMapGraphic()
          + setUnderlayImage()
          + updateField()
          - autoClear()
          - focusClosestNode()
          - updateFieldSize()
      }
    }
  }
  

  namespace gui {
    namespace playfield {
      abstract class gui.playfield.PlayFieldGraphic {
          {static} # scale : double
          {abstract} + draw()
          {static} + getScale()
          {static} + invScale()
          {static} + scale()
          {static} + scale()
          {static} + setScale()
      }
    }
  }
  

  namespace gui {
    namespace playfield {
      class gui.playfield.ScaleReferenceGraphic {
          - FONT_SIZE : int
          - MIN_LENGTH : int
          - REF_COLOR : Color
          - SIZE : int
          - X_POS : int
          - Y_POS : int
          + draw()
      }
    }
  }
  

  gui.playfield.MapGraphic -up-|> gui.playfield.PlayFieldGraphic
  gui.playfield.MapGraphic o-- movement.map.SimMap : simMap
  gui.playfield.MessageGraphic -up-|> gui.playfield.PlayFieldGraphic
  gui.playfield.MessageGraphic o-- core.DTNHost : from
  gui.playfield.MessageGraphic o-- core.DTNHost : to
  gui.playfield.NodeGraphic -up-|> gui.playfield.PlayFieldGraphic
  gui.playfield.NodeGraphic o-- core.DTNHost : node
  gui.playfield.PathGraphic -up-|> gui.playfield.PlayFieldGraphic
  gui.playfield.PlayField -up-|> javax.swing.JPanel
  gui.playfield.PlayField o-- gui.DTNSimGUI : gui
  gui.playfield.PlayField o-- gui.playfield.MapGraphic : mapGraphic
  gui.playfield.PlayField o-- gui.playfield.ScaleReferenceGraphic : refGraphic
  gui.playfield.PlayField o-- core.World : w
  gui.playfield.ScaleReferenceGraphic -up-|> gui.playfield.PlayFieldGraphic


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
